services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=patients'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '65432:5432'
    volumes:
      - patients_data:/var/lib/postgresql/data

volumes:
  patients_data: